### PR TITLE
Add the --lines option to set the maximum output line

### PR DESCRIPTION
**Pull request by yetist**
The Travis CI website has a limit of [10,000](https://travis-ci.org/mate-desktop/caja/jobs/487409953#L10000) lines of output.

If there are too many installation dependencies, you will not see the full build log.

Before, build start at line 2092:
https://travis-ci.org/mate-desktop/caja/jobs/487409954#L2092
After, build start at line 533:
https://travis-ci.org/yetist/caja/jobs/487442500#L533

### CODE REVIEW

**Comment by yetist** [comment]
@raveit65 

Can you enable mate-control-center to support travis? I created a branch to test it: https://github.com/mate-desktop/mate-control-center/tree/travis

**Comment by raveit65** [comment]
Done, it's enabled.

**Comment by raveit65** [comment]
In fedora mock/koji rpm building we use those compiler flags
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I.. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/mate-desktop-2.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/startup-notification-1.0 -I/usr/include/dconf -I/usr/include/gail-3.0 -I/usr/include/libxml2 -pthread -DG_DISABLE_DEPRECATED -DGDK_PIXBUF_DISABLE_DEPRECATED -DDATADIR=\"/usr/share\" -DSYSCONFDIR=\"/etc\" -DCAJA_DATADIR=\"/usr/share/caja\" -DCAJA_EXTENSIONDIR=\"/usr/lib64/caja/extensions-2.0\" -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c caja-desktop-link.c  -fPIC -DPIC -o .libs/caja-desktop-link.o
```
`-Werror=format-security` sounds intresting.

**Comment by raveit65** [comment]
@yetist 
Maybe our basic applications?
mate-panel, metacity, m-s-m ord m-s-d?

**Comment by yetist** [comment]
@raveit65 

Ok, can you enable them on the travis website first? So when I commi, we can see the build log, thank you.

**Comment by raveit65** [comment]
@yetist 
I just enabled mate-desktop, marco, mate-panel, m-s-m and m-s-d.

**Comment by yetist** [comment]
The travis branch is still here, it is Okey.

**Comment by yetist** [comment]
mate-desktop is ready: mate-desktop/mate-desktop#356
marco is ready: mate-desktop/marco#449

**Comment by yetist** [comment]
m-s-d: mate-desktop/mate-settings-daemon#258
m-s-m: mate-desktop/mate-session-manager#185

**Comment by yetist** [comment]
mate-panel is ready: mate-desktop/mate-panel#924

**Pull request merged**
