### PR TITLE
keep the last logs

### PR DESCRIPTION
**Pull request by yetist**
Keep the latest logs.

### CODE REVIEW

**Comment by yetist** [comment]
It is a simple test:
```
$ ls
1  2  3  4  5  6  7  8  9
$ ls -r|tail -n 3
3
2
1
$ ls -r|head -n 3
9
8
7
$ 
```
This changes won't get new issue, let's merge it.

**Comment by sc0w** [comment]
the website is updated with one more commit in caja.

before this PR 10 reports, and with this PR 9 reports:



seems it was removed the two older reports instead one

**Comment by sc0w** [comment]
@yetist 

I like to see 10 reports again, this patch must work?

```patch
diff --git a/travis/gen-index.sh b/travis/gen-index.sh
index e19fc90..3662bff 100755
--- a/travis/gen-index.sh
+++ b/travis/gen-index.sh
@@ -22,7 +22,7 @@ Generate analyzer results index
 EOF
 }
 
-count=10
+count=11
 branch=${TRAVIS_BRANCH}
 owner=${OWNER_NAME}
 name=${REPO_NAME}

**Comment by yetist** [comment]
@sc0w 

10 logs fixed by #18.
10 is the default, if some repo want to use different number, it can change the `.travis.yml` file, and call `gen-index.sh` use `-l 20` to keep the last 20 logs.

**Pull request merged**
