### PR TITLE
Escape the special characters in the commit message

### PR DESCRIPTION
**Pull request by yetist**
fix commit message error on travis.

### CODE REVIEW

**Comment by yetist** [comment]
Test build:
82: https://travis-ci.org/mate-desktop/engrampa/builds/505581981
83: https://travis-ci.org/mate-desktop/engrampa/builds/505584367

**Comment by sc0w** [comment]
@yetist 

I suggest to use the commit message inside single quotes, and it must work with all special chars, only needs to be escaped the `'` char with `'\''`

demostration:

```
scow@debian:~$ echo 'test $""\#=[[ ]]! >, >>, < |;{ }( )(( ))$(( )) *, ? ~& only needs the char '\'' to be escaped'
test $""\#=[[ ]]! >, >>, < |;{ }( )(( ))$(( )) *, ? ~& only needs the char ' to be escaped
scow@debian:~$ 
```

**Comment by yetist** [comment]
After to use single quotes, Restart jobs 82 and 83, let's see the results.

**Comment by yetist** [comment]
Use single quotes, the scripts seems good https://travis-ci.org/mate-desktop/engrampa/jobs/505581982#L386
```
export TRAVIS_COMMIT_MESSAGE='fr-process: Fix memory leak
Fixes Clang static analyzer warning:
fr-process.c:740:3: warning: Potential leak of memory pointed to by \'argv\'
                    g_warning ("The files could not be move: %s\n", commandline);
                    ^~~~~~~~~'
```
But get run error  https://travis-ci.org/mate-desktop/engrampa/jobs/505581982#L436
```
+ export 'TRAVIS_COMMIT_MESSAGE=fr-process: Fix memory leak
Fixes Clang static analyzer warning:
fr-process.c:740:3: warning: Potential leak of memory pointed to by \argv'\'''
+ TRAVIS_COMMIT_MESSAGE='fr-process: Fix memory leak
Fixes Clang static analyzer warning:
fr-process.c:740:3: warning: Potential leak of memory pointed to by \argv'\'''
/rootdir/before_scripts: line 15: syntax error near unexpected token `"The files could not be move: %s\n",'
```

**Comment by sc0w** [comment]
`new_msg = raw_msg.replace("'", "\\\'")`

this line is wrong

try with

`new_msg = raw_msg.replace("'", "'\''")`

**Comment by sc0w** [comment]
or with this?

`new_msg = raw_msg.replace("'", "\'\\\'\'")`

I don't know how it works the function, but I mean `'` must be replaced by `'\''` in bash

**Comment by yetist** [comment]
> `new_msg = raw_msg.replace("'", "\\\'")`
> 
> this line is wrong
> 
> try with
> 
> `new_msg = raw_msg.replace("'", "'\''")`

It failed, all test builds are 82, 83, and 84, links can found from here: https://travis-ci.org/mate-desktop/engrampa/builds

**Comment by sc0w** [comment]
@yetist  and this?

`new_msg = raw_msg.replace("'", "\'\\\'\'")`

**Comment by sc0w** [comment]
```
scow@debian:~$ export TRAVIS_COMMIT_MESSAGE='test $""\#=[[ ]]! >, >>, < |;{ }( )(( ))$(( )) *, ? ~& only needs the char '\'' to be escaped'
scow@debian:~$ echo $TRAVIS_COMMIT_MESSAGE
test $""\#=[[ ]]! >, >>, < |;{ }( )(( ))$(( )) *, ? ~& only needs the char ' to be escaped
scow@debian:~$ 
```

**Comment by yetist** [comment]
There are now 3 test cases:
82 is a normal commit message, it include clang report lines.
83 's commit message is a normal perl scripts.
84 's commit message consists of many special characters, it coms from above comments https://github.com/mate-desktop/mate-dev-scripts/pull/15#issuecomment-472424356

**Comment by rbuj** [comment]
I think that use %r instead of %s can help to solve it.
```python
fp.write ('export %s="%r"\n' % (var, new_msg))
```

**Comment by sc0w** [comment]
all the travis checks seems to be ok now

**Comment by sc0w** [comment]
only left to squash all the commits in one

@yetist thanks, now we never will have problems in future commit messages :)

**Comment by yetist** [comment]
> only left to squash all the commits in one
> 
Done, it is ready to merge.

**Pull request merged**
