### PR TITLE
Travis support

### PR DESCRIPTION
**Pull request by yetist**
Maybe we can try Travis-CI?
Please read the [README](https://github.com/mate-desktop/mate-dev-scripts/blob/704f5f853e2eef27fc6d2fd576b3241af965a580/travis/README.md) for more details.

### CODE REVIEW

**Comment by yetist** [comment]
I tested it to compile mate-notification-daemon on travis, https://travis-ci.org/yetist/mate-notification-daemon/builds/479327210
Build log on archlinux: https://travis-ci.org/yetist/mate-notification-daemon/jobs/479327211
Build log on fedora 29: https://travis-ci.org/yetist/mate-notification-daemon/jobs/479327212
Build log on ubuntu 18.04: https://travis-ci.org/yetist/mate-notification-daemon/jobs/479327213

**Comment by lukefromdc** [comment]
Leaving this for others, as I don't know anything at all about Travis

**Comment by raveit65** [comment]
I like the idea to have a quick build check for all major distros that we support.
Maybe we can add debian to .docker.json in repos, they support docker images too, as far i know.
Not sure about centos7, most packages are equal to fedora.
Can you provide steps how to use this script with travis, please.
I quess you need an account by travis or will the github account be used?

As a long term we should use automatic travis builds for every repo.

**Comment by raveit65** [comment]
Ok, docker-build is a python script.
Did you run this script inside a repo?

**Comment by yetist** [comment]
I wrote this script to build all mate projects instead of providing a build script in each repos, which saves a lot of maintenance and keeps the repo clean.

The following are the different types of a project updates and what triggers a build run for each:
- Branch: Every time a new branch is created or the commit its HEAD points to changes;
- Pull Request: Every time a pull request is created or if it's associated branches change in any way;
- Tag: Every time a new tag is created or its commit changes;
Whether Branch, pull request, and Tag trigger Travis to start work depends on the .travis.yml  configuration file in each repos, which must exist.

Because different project needs different dependencies when it is built,  so `.docker.json` file is added to each project repo. It used to set which dependency packages should be installed when compiling in different distributions.

If we want to enable Travis for mate-notification-daemon project, here are the steps:
1. Add the file `.travis.yml` to the top level directory of mate-notification-daemon project. The contents can be as follows:
```
sudo: required
services:
  - docker

before_install:
  - curl -L -o docker-build https://raw.githubusercontent.com/mate-desktop/mate-dev-scripts/travis/travis/docker-build
  - chmod +x docker-build
 
install:
  - ./docker-build --name ${DISTRO} --verbose --install

script:
  - ./docker-build --name ${DISTRO} --verbose --build make

env:
  - DISTRO="base/archlinux"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"
```
More custom settings can be found here: https://docs.travis-ci.com/user/customizing-the-build

2. Add the file `.docker.json` to the top level directory of mate-notification-daemon software repository. The contents can be as follows:
```
{
  "requires" : {
    "archlinux" : [
	  "gcc",
	  "git",
	  "gtk3",
	  "intltool",
	  "libnotify",
	  "libwnck3",
	  "make",
	  "mate-common"
    ],
    "fedora" : [
	  "desktop-file-utils",
	  "git",
	  "libcanberra-devel",
	  "libnotify-devel",
	  "libwnck3-devel",
	  "mate-common",
	  "mate-desktop-devel"
    ],
    "ubuntu" : [
	  "git",
	  "gobject-introspection",
	  "gtk-doc-tools",
	  "intltool",
	  "libcanberra-gtk3-dev",
	  "libdconf-dev",
	  "libexempi-dev",
	  "libexif-dev",
	  "libgail-3-dev",
	  "libgirepository1.0-dev",
	  "libglib2.0-dev",
	  "libgtk-3-dev",
	  "libmate-desktop-dev",
	  "libnotify-dev",
	  "libpango1.0-dev",
	  "libstartup-notification0-dev",
	  "libwnck-3-dev",
	  "libx11-dev",
	  "libxml2-dev",
	  "mate-common",
	  "quilt",
	  "shared-mime-info"
    ]
  },
  "distcheck" : true
}
```
The `docker-build` script installs dependency and compilation projects by parsing this file.
If it's not mate-notification-daemon, then the dependency packages in the `.docker.json` file need to be adjusted, because I only tested and validated mate-notification-daemon.

3. That's all.

**Comment by raveit65** [comment]
I will merge it. let see how it works.
Thanks.

**Comment by raveit65** [comment]
Btw. i added your configs to a new branch of  n-m-d for testing. 
https://github.com/mate-desktop/mate-notification-daemon/pull/142
I guess this needs to be merged before it starts working?

**Comment by raveit65** [comment]
Hmm, i just forked m-n-d repo to https://github.com/raveit65/mate-notification-daemon
and merged the travis config.
https://github.com/raveit65/mate-notification-daemon/commit/b223bd25b93abf6e9bf6bdec6d8039b1c41e312c
Than i did a new PR for testing 
https://github.com/raveit65/mate-notification-daemon/pull/2
But i don't see any links to travis-Ci build there.
When the travis build will be triggered?
When a PR is open or when it will be merged?

**Comment by yetist** [comment]
@raveit65 
Maybe you didn't  login the website https://travis-ci.org, you should enable your `raveit65/mate-notification-daemon` to use travis in that website.

I visited https://travis-ci.org/raveit65/mate-notification-daemon/,  I saw it show me that: "We couldn't find the repository."

**Comment by clefebvre** [comment]
Hi @yetist,

That's really cool. It'd be nice to see CI build checks on commits and PRs, and Travis is a very good choice.

**Pull request merged**
