### PR TITLE
Improve local debugging and archlinux/base image support

### PR DESCRIPTION
**Pull request by yetist**
Save time by using ~/.distro_hook instead of creating it in every source directory.
Support both `base/archlinux` and `archlinux/base` images.

### CODE REVIEW

**Comment by yetist** [comment]
Archlinux does not have an official docker image and requires special handling.
It seems that you should use the `archlinux/base` image.
```
$ docker search archlinux
NAME                                  DESCRIPTION                                     STARS               OFFICIAL            AUTOMATED
base/archlinux                        Deprecated repository, use archlinux/base in…   333                                     [OK]
pritunl/archlinux                     NO LONGER MAINTAINED                            101                                     
archlinux/base                        Docker Base Image for Arch Linux                58                                      
```

**Comment by yetist** [comment]
Test here:   https://github.com/mate-desktop/marco/pull/451

**Comment by monsta** [comment]
@yetist: do you use Arch? Because nobody else from the team uses it, so we wouldn't know how to fix things if something breaks...

**Comment by yetist** [comment]
Yes, I use Archlinux, but not the Archlinux maintainer.

**Comment by monsta** [comment]
Ok :slightly_smiling_face:

**Pull request merged**
