### PR TITLE
Add new features

### PR DESCRIPTION
**Pull request by yetist**
New features:
1. Support both json and yaml formatted configuration files.
2. Support both autotools and meson build systems.
3. Can add environment variables at compile time
4. Use before_scripts and after_scripts instead of prebuild and postbuild.
5. The BUILD_TYPE variable can be used in after_scripts.

### CODE REVIEW

**Comment by yetist** [comment]
# yaml config example:
.travis.yml: https://github.com/yetist/mate-notification-daemon/blob/travis/.travis.yml
.docker-build.yml: https://github.com/yetist/mate-notification-daemon/blob/travis/.docker-build.yml
build log: https://travis-ci.org/yetist/mate-notification-daemon/builds/485277445

# meson build example:
.travis.yml: https://github.com/yetist/lunar-date/blob/master/.travis.yml
.docker-build.yml: https://github.com/yetist/lunar-date/blob/master/.docker-build.yml
build log: https://travis-ci.org/yetist/lunar-date/builds/485284861

**Comment by yetist** [comment]
@raveit65 
I think it's ready to use for all mate-desktop projects.
Here is an example for autotools:
https://travis-ci.org/mate-desktop/mate-notification-daemon/builds/486849607
And this example for meson:
https://travis-ci.org/yetist/lunar-date/builds/486803947

Now we need to add one `.travis.yml` file only.

**Comment by yetist** [comment]
@raveit65 

I added Travis CI support for caja, but I don't have permission to enable it on the travis-ci.org website. Can you do it? Thank you.

https://github.com/mate-desktop/caja/blob/travis/.travis.yml

**Comment by raveit65** [comment]
> I added Travis CI support for caja, but I don't have permission to enable it on the travis-ci.org website. Can you do it? Thank you.

Done, should be work now when travis config is in master

**Comment by raveit65** [comment]
Btw. ubuntu and debian build requires are mostly the same, see debian-packages repo.
https://github.com/mate-desktop/debian-packages/blob/master/caja/debian/control
It should be save to enable debian too.

**Comment by raveit65** [comment]
Btw. build dependencies for fedora you can take from fedora git.
https://src.fedoraproject.org/cgit/
for caja:
https://src.fedoraproject.org/cgit/rpms/caja.git/tree/caja.spec
Those build requires are used to build official mate packages on fedora build server (koji)
I never used `redhat-rpm-config` for caja ;)

**Comment by raveit65** [comment]
Ok, so .docker.json is changed to .docker-build.yml in repos.
Looks good for me, i will merge it.

**Comment by yetist** [comment]
@raveit65 

That `redhat-rpm-config` is needed, please see the build log: https://travis-ci.org/mate-desktop/caja/jobs/486918137

The `dnf groupinstall build` command will install `redhat-rpm-config` into koji/mock, see the `root.log` here: https://kojipkgs.fedoraproject.org//work/tasks/3878/32363878/root.log

**Comment by yetist** [comment]
@raveit65 

That `redhat-rpm-config` is needed, please see the build log: https://travis-ci.org/mate-desktop/caja/jobs/486918137

The `dnf groupinstall build` command will install `redhat-rpm-config` into koji/mock, see the `root.log` here: https://kojipkgs.fedoraproject.org//work/tasks/3878/32363878/root.log

**Comment by yetist** [comment]
> Ok, so .docker.json is changed to .docker-build.yml in repos.

Yes, adding comments to a json file is difficult, so use the yaml format now.

**Comment by raveit65** [comment]
> The `dnf groupinstall build` command will install `redhat-rpm-config` into koji/mock, see the `root.log` 

Ok, you're right, than we need to add all build requires from scratch, which are more than in my fedora SPEC files.
But they can use as templates.

**Comment by raveit65** [comment]
```
  GISCAN   Caja-2.0.gir
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python3.7/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
  File "/usr/lib64/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```
```
[root@mother rave]# dnf provides /usr/lib/rpm/redhat/redhat-hardened-cc1
Letzte Prüfung auf abgelaufene Metadaten: vor 2:05:47 am Do 31 Jan 2019 12:17:24 CET.
redhat-rpm-config-110-1.fc28.noarch : Red Hat specific rpm configuration files
Quelle      : @System
Übereinstimmung von:
Dateiname     : /usr/lib/rpm/redhat/redhat-hardened-cc1
```

**Pull request merged**
