### PR TITLE
Auto release version on github and notify custom servers

### PR DESCRIPTION
**Pull request by yetist**
- Update version to 0.1.1
- Auto release version on github when push tag
- Notify servers to download release files from github
- Support for writing custom commands to run builds
- Use the make -j parameter if possible
- Optimized output message omitted
- Update README.md
- Update template.yml
- Update distro_hook
- Dependent on github python module

*EDIT:*
If it is running on Travis, need to add the following lines before running docker-build:
```
Install:
   - sudo apt-get install -y python3-pip python3-setuptools
   - sudo pip3 install --upgrade pip
   - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install
```

So, before merge this PR to master, need to modify the existing .travis.yml, otherwise the build will be breaked.

### CODE REVIEW

**Comment by yetist** [comment]
How to use automatic publishing?
1. Copy templa.yml to .travis.yml and confirm the following:
```
...
deploy:
  provider: script
  script: ./docker-build --name ${DISTRO} --verbose --config .travis.yml --release
  skip_cleanup: true
  on:
    tags: true
    condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"
...
releases:
  draft: False
  prerelease: False
  checksum: True
  base_version: 1.20.0
  file_glob: True
  files: EXAMPLE-*.tar.xz           #comment 1
  servers:                              #comment 2
    - http://pub.mate-desktop.org/releases/
```
comments:
- comment 1: `files`, it will match the tarballs file name and need to be modified.
- comment 2: `servers`, when the version is successfully released on github, the servers here will receive the post request. After the server resolves the request, it knows which files should be downloaded for public release. If the server is not ready, you can delete the `servers` section.

2. Enable CI service for repo on the travis website.
URL: https://travis-ci.org/account/repositories

3.  Create a github personal access token using the `public_repo` and `user:email` scopes.
Personal access tokens created using the `repo` and `user` scopes are also available.
URL: https://github.com/settings/tokens/new

4. Setup the github personal access token value to the hidden environment variables named 'GITHUB_TOKEN' on the travis-ci website.
reference: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

5. Ok, now you can create a tag and push it to github.

Note that the release notes will be generated from the NEWS file. If there is no such file, it will be generated from the previous tag to the HEAD's commit log.

**Comment by raveit65** [comment]
For better understanding, whole the process starts with a release tag in repo?
I just created a personal token (3), but i don`t understand what i should do in point (4)?

**Comment by raveit65** [comment]
> 4. Setup the github personal access token value to the hidden environment variables named 'GITHUB_TOKEN' on the travis-ci website.
reference: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

Where at travic-CI ? For example `https://travis-ci.org/mate-desktop/mate-common`
In settings there?

**Comment by yetist** [comment]
The point 4 is, create a git tag by run `git tag -a`, and push the tag to github by run `git push`.

**Comment by raveit65** [comment]
Hmm, isn't that point 5 ?

**Comment by yetist** [comment]
see here , https://travis-ci.org/mate-desktop/mate-common/settings, I setup the variable, but the value is not correct, you should change it.

**Comment by raveit65** [comment]
Ok, i found the place of GITHUB_TOKEN var. 
bildschirmfoto zu 2019-02-16 19-44-00
Here i should add my user-name to name field and the secret value from the personal token in the value field, right?

**Comment by raveit65** [comment]
Again, i have no idea what i should file out in the screenshot under https://github.com/mate-desktop/mate-dev-scripts/pull/13#issuecomment-464371363

**Comment by yetist** [comment]
> Again, i have no idea what i should file out in the screenshot under [#13 (comment)](https://github.com/mate-desktop/mate-dev-scripts/pull/13#issuecomment-464371363)

Nothing to do now, I just set the GITHUB_TOKEN variable with my valid token.

I created a branch travis-autorelease for mate-common, after it merges into master, if everything goes well, then push any tag it will create release version on github and send notification to some server.

**Comment by raveit65** [comment]
> Nothing to do now, I just set the GITHUB_TOKEN variable with my valid token.

Ok, but may be it helps if some other person like you understand how to set up this?

**Comment by yetist** [comment]
Of course, we can first test on a personal repo.
Step by step for personal repo test:
1. fork the mate-desktop/mate-common repo.
2. open https://travis-ci.org/account/repositories, "Sync account" and enable personal mate-common repo on travis ci, then set the GITHUB_TOKEN variable with your valid token for this repo.
3. do the follow commands:
```
$ git clone https://github.com/mate-desktop/mate-common.git
$ cd mate-common/
$ git merge origin/travis-autorelease
$ git remote add myown git@github.com:yetist/mate-common.git #replace yetist with your username
$ git push myown master
```
OK, now it's ready.

4. The next step is to use git normally.
If someone git push tag, the release will be created automatically.
For example:
```
$ vim NEWS
$ head NEWS
### mate-common 1.21.1

  * bump version
  * This version just for test.

### mate-common 1.21.0

  * bump version

### mate-common 1.20.0
$ git commit -am "test it"
$ git push myown master
$ git tag -a v1.21.1 -m "version 1.21.1"
$ git push myown v1.21.1
```
Now you can see the release here: https://github.com/yetist/mate-common/releases
And the custom release server will be notified: https://travis-ci.org/yetist/mate-common/jobs/494788790#L700

**Comment by raveit65** [comment]
Again, i don't understand what should i type in this mask.
bildschirmfoto zu 2019-02-16 19-44-00
There are 3 fields!!!

**Comment by yetist** [comment]
> Again, i don't understand what should i type in this mask.
> bildschirmfoto zu 2019-02-16 19-44-00
> There are 3 fields!!!

The `Name` field must be write `GITHUB_TOKEN`(docker-build use this name), the `Value` field write your github personal access token.

Please ignore the third field and leave it unchecked. If the value displayed in the build log, anyone will see your token, which is very insecure.

**Comment by yetist** [comment]
Write the first and the second field, then click the "Add" button.

**Comment by raveit65** [comment]
Got it, thanks for this important information not to use the field with the lock icon.
I will test all later, need to do some things in real live.

**Comment by raveit65** [comment]
Ok, now i understood the screenshot, there was already a GITHUB_TOKEN from you...
I followed your instructions and enabled travis, added my token to forked mate-common, but release page looks like before.
https://github.com/raveit65/mate-common/releases

**Comment by raveit65** [comment]
> I followed your instructions and enabled travis, added my token to forked mate-common, but release page looks like before.
https://github.com/raveit65/mate-common/releases

Forgot what i said, after half an our the page is there :)
Where the mate-common-1.21.1.tar.xz tarball was build?
On travis server?

**Comment by yetist** [comment]
Yes, on travis, the result of `make distcheck` is used. The current setting is to use tarballs generated on fedora.
```
    condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"
```
You can do more tests next, such as after the release of 1.22, continue to release the 1.20.x version on the 1.20 branch and so on.

If all this works well, then there are two things to do:
1. Let all repos use travis.
2. Write the server-side http program to receive the release notification, and download the tarballs file, checksum file from github release, and can create news files for the current release.

**Comment by raveit65** [comment]
A mate desktop release will usually happen like this.
We (maybe me) commit a release of a repo and upload all tarballs to pre-release folder at our server.
Here members can test the tarballs. But no tag is done at this point.
I asked @flexiondotorg to give you and all new members of core-team a sftp access to this folder. 
If all is done and all tarballs are created, than @flexiondotorg
1. publish the release notes at server, 
2. tag the release commits 
3. moves the tarballs from pre-release to  internal release folder (sftp).
An internal script at server moves the tarballs to public release folder.
Now 1.22 is released!

So, i think we can use creating the github release page for the release for some repos, eg. mate-common.
Maybe we disable the server notification part for the moment?
To avoid that the fedora branch at travis, which creates the tarball for the github relese page, displays failure status.

**Comment by raveit65** [comment]
Ok, disabling server notifications works fine.
https://github.com/raveit65/mate-common/commit/15ecc1a5d1a851c9794dc1cd0b1a2efd15af2018
Tarball is released and all checks at travis are satisfied.
https://github.com/raveit65/mate-common/releases
https://travis-ci.org/raveit65/mate-common/builds/495381217?utm_source=github_status&utm_medium=notification

You did a fantastic job.

**Comment by yetist** [comment]
Description of the release section:
```
releases:
  draft: False             # if True, to create a draft for release
  prerelease: False   # if True, create a prelease version
  checksum: True    # if True, auto generate sha256sum file for the tarball, False do nothing
  overwrite: True     # if exists a same named tag on server, first delete that tag, then create new tag.
  base_version: 1.20.0  # base version, if no tags exists on server, use this as previous version to generate release notes.
  file_glob: True       # if True, item in the files use glob to get full path, if False , item in the files is the full path.
  files: EXAMPLE-*.tar.xz # files to upload for release, support fullpath or pathname pattern expansion.
  custom_http_headers:  # docker-build can use custom http header to server  when send post message.
    - "User-Agent = release-bot/0.1.1 (Travis CI)" # name=value to send server by http header
    - Release-Token = $SERVER_POST_TOKEN  # the value begin with $ to use environment variables.
  servers:
    - http://pub.mate-desktop.org/releases/ # which url will receive the http POST data.
```

**Comment by yetist** [comment]
1.22 Release Please continue to use the current method.
I hope to test and improve docker-build in the 1.23 development phase, and hope that all work can be automated when the 1.24 release.

**Comment by raveit65** [comment]
> 1.22 Release Please continue to use the current method.

Like you want....

>     1. Let all repos use travis.

I am starting adding libmatekbd and the other libmate repos for myself to travis.

**Comment by yetist** [comment]
Update the docker-build version to 0.1.2, may be it's ready to merge.

The last thing is to write a release server for testing.

**Comment by yetist** [comment]
@mate-desktop/core-team

I think this is ready, is it time to merge into the master branch?

**Comment by yetist** [comment]
Start writing the release server,  https://github.com/yetist/release-server

@raveit65 

This PR can be merged into the master branch so that we can open more repos to use the clang analyzer.

**Comment by raveit65** [comment]
Ok, let the beast run.

**Comment by raveit65** [comment]
We can delete branch later, maybe we need it again.

**Comment by yetist** [comment]
No one is using this branch anymore, it's time to delete it.

**Comment by yetist** [comment]
@raveit65 

The release server just works. 

Here is a demo release website: https://mate.zhcn.cc/
I use this repo for test: https://github.com/yetist/mate-common

**Comment by raveit65** [comment]
@yetist 
looks nice:)
I will open a new issue for this where we can work on it, together with @flexiondotorg

**Comment by raveit65** [comment]
Done https://github.com/mate-desktop/mate-dev-scripts/issues/23

**Pull request merged**
